export const moravickiOkrugPathRoutes = {
    home: "/sumadijaTekstModal/SumadijaIZapadnaSrbija/MoravickiOkrug",
    cacak: "/sumadijaTekstModal/SumadijaIZapadnaSrbija/MoravickiOkrug/Cacak",
    ovcarskoKablarskaKlisura: "/sumadijaTekstModal/SumadijaIZapadnaSrbija/MoravickiOkrug/OvcarskoKablarskaKlisura",
    manastirJovanje: "/sumadijaTekstModal/SumadijaIZapadnaSrbija/MoravickiOkrug/OvcarskoKablarskaKlisura/ManastirJovanje",
    manastirNikolje: "/sumadijaTekstModal/SumadijaIZapadnaSrbija/MoravickiOkrug/OvcarskoKablarskaKlisura/ManastirNikolje",
    manastirPreobrazenje: "/sumadijaTekstModal/SumadijaIZapadnaSrbija/MoravickiOkrug/OvcarskoKablarskaKlisura/ManastirPreobrazenje",
    manastirSavinje: "/sumadijaTekstModal/SumadijaIZapadnaSrbija/MoravickiOkrug/OvcarskoKablarskaKlisura/ManastirSavinje",
    manastirSveteTrojice: "/sumadijaTekstModal/SumadijaIZapadnaSrbija/MoravickiOkrug/OvcarskoKablarskaKlisura/ManastirSveteTrojice",
    manastirUspenje: "/sumadijaTekstModal/SumadijaIZapadnaSrbija/MoravickiOkrug/OvcarskoKablarskaKlisura/ManastirUspenje",
    manastirVavedenje: "/sumadijaTekstModal/SumadijaIZapadnaSrbija/MoravickiOkrug/OvcarskoKablarskaKlisura/ManastirVavedenje",
    manastirVaznesenje: "/sumadijaTekstModal/SumadijaIZapadnaSrbija/MoravickiOkrug/OvcarskoKablarskaKlisura/ManastirVaznesenje",
    jezeroMedjuvrsje: "/sumadijaTekstModal/SumadijaIZapadnaSrbija/MoravickiOkrug/JezeroMedjuvrsje",
    manastirBlagovestenje: "/sumadijaTekstModal/SumadijaIZapadnaSrbija/MoravickiOkrug/ManastirBlagovestenje",
    guca: "/sumadijaTekstModal/SumadijaIZapadnaSrbija/MoravickiOkrug/Guca",
    gornjiMilanovac: "/sumadijaTekstModal/SumadijaIZapadnaSrbija/MoravickiOkrug/GornjiMilanovac",
    planinaRudnik: "/sumadijaTekstModal/SumadijaIZapadnaSrbija/MoravickiOkrug/PlaninaRudnik",
    manastirSretenje: "/sumadijaTekstModal/SumadijaIZapadnaSrbija/MoravickiOkrug/ManastirSretenje",
    
}