export const sumadijskiOkrugPathRoutes = {
    home: (lang) => `/${lang}/sumadija-tekst-modal/sumadija-i-zapadna-srbija/sumadijski-okrug`,
    kragujevac: (lang) => `/${lang}/sumadija-tekst-modal/sumadija-i-zapadna-srbija/sumadijski-okrug/kragujevac`,
    staraPridvornaCrkva: (lang) => `/${lang}/sumadija-tekst-modal/sumadija-i-zapadna-srbija/sumadijski-okrug/kragujevac/stara-pridvorna-crkva`,
    konakKnezaMihaila: (lang) => `/${lang}/sumadija-tekst-modal/sumadija-i-zapadna-srbija/sumadijski-okrug/kragujevac/konak-kneza-mihaila`,
    zgradaGimnazije: (lang) => `/${lang}/sumadija-tekst-modal/sumadija-i-zapadna-srbija/sumadijski-okrug/kragujevac/zgrada-gimnazije`,
    ZgradaStareLivnice: (lang) => `/${lang}/sumadija-tekst-modal/sumadija-i-zapadna-srbija/sumadijski-okrug/kragujevac/zgrada-stare-livnice`,
    spomenikStarimSumadincima: (lang) => `/${lang}/sumadija-tekst-modal/sumadija-i-zapadna-srbija/sumadijski-okrug/kragujevac/spomenik-palim-sumadincima`,
    arandjelovac: (lang) => `/${lang}/sumadija-tekst-modal/sumadija-i-zapadna-srbija/sumadijski-okrug/arandjelovac`,
    oplenac: (lang) => `/${lang}/sumadija-tekst-modal/sumadija-i-zapadna-srbija/sumadijski-okrug/oplenac`,
    gruzanskoJezero: (lang) => `/${lang}/sumadija-tekst-modal/sumadija-i-zapadna-srbija/sumadijski-okrug/gruzansko-jezero`,
    manastirBlagovestenjeRudnicko: (lang) => `/${lang}/sumadija-tekst-modal/sumadija-i-zapadna-srbija/sumadijski-okrug/manastir-blagovestenje-rudnciko`,
    manastirPetkovica: (lang) => `/${lang}/sumadija-tekst-modal/sumadija-i-zapadna-srbija/sumadijski-okrug/manastir-petkovica`,
    planinarskaStazaZezeljIBesnjaja: (lang) => `/${lang}/sumadija-tekst-modal/sumadija-i-zapadna-srbija/sumadijski-okrug/zezelj-i-besnjaja`,
}